### ISSUE TITLE
Uncaught ReferenceError: iFrameResize is not defined

### ISSUE THREAD

**Issue by rohit-kalra** [B-Translator/discourse-embedded-comments#1]
I installed the plugin to my discourse forum and rebuild the app following the commands.
But I ran into the error 
`GET http://my-blog-site.com/my-topic/lib/iframeResizer.min.js`
followed by the errors
`Uncaught ReferenceError: iFrameResize is not defined`
`Refused to display 'https://my-forum-site.com/t/my-topic/30' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

I explicitly copied and pasted the code of file _iframeResizer.contentWindow.min.js_ but the error persisted.
Can you help me with what I may be missing ?
Thanks..

**Comment by dashohoxha** [comment]
I think that there are 2 parts of iFrameResizer, see here:
https://github.com/davidjbradshaw/iframe-resizer/tree/master/src
So, maybe you have copied the wrong file.

It is my mistake that I have not explained it clearly on the README. This needs to be fixed.

The SAMEORIGIN issue is a different problem, see this:
https://github.com/B-Translator/discourse-allow-same-origin

**Comment by rohit-kalra** [comment]
Thanks @dashohoxha 
Worked like a charm.. Embedding of the topic works fine now. 
But I still am getting this error..
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://my-forum-site.com') does not match the recipient window's origin ('http://my-blog-site.com').`
Is this related to the fact that my **forum server** is secure and my **blog server** is not ?

**Comment by rohit-kalra** [comment]
It was just one time error and it got fixed. :)
Thanks for the help once again @dash
